import = [
  # "~/.config/alacritty/themes/catppuccin-macchiato.toml"
  # "~/.config/alacritty/themes/catppuccin-mocha.toml"
  "~/.config/alacritty/themes/rose-pine.toml"
]

[env]
TERM = "xterm-256color"
LANG = "en_US.UTF-8"
LC_CTYPE = "en_US_UTF-8"

[font]
size = 14
bold.family = "DejaVu Sans Mono"
bold.style = "Bold"
glyph_offset.x = 1
glyph_offset.y = 0
italic.family = "DejaVu Sans Mono"
italic.style = "Italic"
normal.family = "DejaVu Sans Mono"
offset.x = 1
offset.y = 0

[window]
padding.x = 5
padding.y = 5
decorations = "Full"
decorations_theme_variant = "Dark"

