import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"
LANG = "en_US.UTF-8"
LC_CTYPE = "en_US.UTF-8"

[font]
size = 13

[font.bold]
family = "DejaVu Sans Mono"
style = "Bold"

[font.glyph_offset]
x = 1
y = 0

[font.italic]
family = "DejaVu Sans Mono"
style = "Italic"

[font.normal]
family = "DejaVu Sans Mono"
styles = "Regular"

[font.offset]
x = 1
y = 0

[window]
padding.x = 5
padding.y = 5
decorations = "Full"
decorations_theme_variant = "Dark"

